# Generated by Django 4.1.2 on 2022-11-01 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artiest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Artiesten',
            },
        ),
        migrations.CreateModel(
            name='Kamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdieping', models.IntegerField()),
                ('kamer_identificatie', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Kamers',
            },
        ),
        migrations.CreateModel(
            name='OverheidsGebouw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adres', models.CharField(max_length=30)),
                ('postcode', models.CharField(max_length=6)),
                ('stad', models.CharField(max_length=20)),
                ('pand_code', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Overheidsgebouwen',
            },
        ),
        migrations.CreateModel(
            name='Kunstwerk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=30)),
                ('beschrijving', models.TextField(blank=True)),
                ('lengte', models.IntegerField(null=True)),
                ('breedte', models.IntegerField(null=True)),
                ('hoogte', models.IntegerField(null=True)),
                ('artiesten', models.ManyToManyField(to='api.artiest')),
                ('locatie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.kamer')),
            ],
            options={
                'verbose_name_plural': 'Kunstwerken',
            },
        ),
        migrations.AddField(
            model_name='kamer',
            name='gebouw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.overheidsgebouw'),
        ),
    ]
